"""Abstract storage interface for the cloud dashboard.

Two implementations:
  - SqliteStorage   (stdlib sqlite3, for tests and local dev)
  - PostgresStorage  (psycopg2, for production on Railway)

Switching is done via env DATABASE_URL in storage_factory.py.
This protocol defines the contract so both backends are interchangeable.
"""

from __future__ import annotations

from typing import Any, Optional, Protocol, runtime_checkable

from mcp_shield.cloud.models import ApiKey, Event, Org, User


@runtime_checkable
class Storage(Protocol):
    """Database backend contract. Every method is org-scoped (multi-tenant)."""

    # --- lifecycle ---
    def close(self) -> None: ...

    # --- orgs ---
    def create_org(self, name: str) -> Org: ...
    def get_org(self, org_id: str) -> Optional[Org]: ...

    # --- users ---
    def create_user(self, org_id: str, email: str, password_hash: str, role: str) -> User: ...
    def get_user_by_email(self, email: str) -> Optional[User]: ...
    def get_user(self, user_id: str) -> Optional[User]: ...
    def list_users(self, org_id: str) -> list[User]: ...
    def update_password(self, user_id: str, new_hash: str) -> bool: ...
    def delete_user(self, user_id: str) -> bool: ...
    def update_user_role(self, user_id: str, role: str) -> bool: ...
    def count_admins(self, org_id: str) -> int: ...

    # --- api keys ---
    def create_api_key(self, org_id: str, label: str, scopes: list[str] | None = None) -> ApiKey: ...
    def validate_api_key(self, key: str) -> Optional[ApiKey]: ...
    def revoke_api_key(self, key: str) -> bool: ...
    def list_api_keys(self, org_id: str) -> list[ApiKey]: ...

    # --- events ---
    def insert_event(self, org_id: str, entry: dict[str, Any]) -> bool: ...
    def query_events(
        self,
        org_id: str,
        *,
        decision: Optional[str] = None,
        server: Optional[str] = None,
        tool: Optional[str] = None,
        start: Optional[str] = None,
        end: Optional[str] = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[Event]: ...
    def count_events(self, org_id: str, *, decision: Optional[str] = None) -> int: ...
    def get_event(self, org_id: str, event_id: int) -> Optional[Event]: ...
    def summary(self, org_id: str, *, start: Optional[str] = None, end: Optional[str] = None) -> dict[str, int]: ...
    def delete_old_events(self, days: int) -> int: ...
